# Generated by Django 3.2.7 on 2021-09-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(default='', max_length=256, verbose_name='User')),
                ('rows', models.SmallIntegerField(default=0, verbose_name='Rows')),
                ('columns', models.SmallIntegerField(default=0, verbose_name='Columns')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('mines', models.SmallIntegerField(default=0, verbose_name='Mines')),
                ('state_time_elapsed', models.IntegerField(default=0, verbose_name='Time elapsed')),
                ('state_board', models.TextField(default='', verbose_name='json')),
            ],
        ),
    ]
