# Generated by Django 3.2.7 on 2021-09-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('STARTED', 'Started'), ('WON', 'Won'), ('LOST', 'Lost')], default='NOT_STARTED', max_length=11, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='game',
            name='state_board',
            field=models.TextField(default='[]', verbose_name='json'),
        ),
    ]
